version: "3.8"

services:
  mysqldb:
    #image: mysql:5.7
    build: ./mysql  # si vous avez un Dockerfile personnalisé
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achat_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  
  backend-app:
    depends_on:
      - mysqldb
    build: ./backend  # construit à partir du Dockerfile dans le dossier backend
    image: backendimage
    image: bdimage
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/achat_db?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'

volumes:
  db: